- README.md
- cmd/sfncli/runner.go
- cmd/sfncli/sfncli.go
- sfcli now validates that it's input and output are json objects
- validates that its input and output include `$execution-name`
- an env-var called `_EXECUTION_NAME` is injected into the execution context of the sub-process
Jira: https://clever.atlassian.net/browse/INFRA-2553, https://clever.atlassian.net/browse/INFRA-2526
> Added input/output validation and passed execution-name to worker

- cmd/sfncli/runner.go
- cmd/sfncli/sfncli.go
Found myself looking for this feature when confirming that cil-reliability-dashboard ran correctly last night.
It might be worth to using `wf_id` instead to be consistent with how workers log workflow_id.
cc @rgarcia @mohit
> Include execution name in logs to make debugging easier

- .gitignore
- Makefile
- README.md
- cmd/sfncli/error_names.go
- cmd/sfncli/runner.go
- cmd/sfncli/runner_test.go
- cmd/sfncli/sfncli.go
- cmd/sfncli/test_scripts/log_to_stderr_and_wait.sh
- cmd/sfncli/test_scripts/signal_echo.sh
- cmd/sfncli/test_scripts/stderr_stdout_exitcode.sh
- cmd/sfncli/test_scripts/stderr_stdout_exitcode_onsigterm.sh
- cmd/sfncli/test_scripts/stderr_stdout_loopforever.sh
- cmd/sfncli/test_scripts/stdout_parsing.sh
- glide.lock
- glide.yaml
https://clever.atlassian.net/browse/INFRA-2542
1. Adds the following built-in error names:
- `sfncli.TaskInputNotJSON`: input to the task was not JSON
- `sfncli.CommandNotFound`: the command passed to `sfncli` was not found
- `sfncli.CommandKilled`: the command process received SIGKILL
- `sfncli.CommandExitedNonzero`: the command process exited with a nonzero exit code
- `sfncli.TaskOutputNotJSON`: the task output (last line of command's stdout) was not JSON
- `sfncli.CommandTerminated`: `sfncli` received SIGTERM
- `sfncli.Unknown`: unexpected / unclassified errors
In practice the most common one will be `sfncli.CommandTerminated`, which will happen any time we deploy a new worker and ECS / docker stops containers via SIGTERM.
2. JSON output of a task now taken from the last non-empty …
> produce useful error names

- cmd/sfncli/runner.go
- cmd/sfncli/runner_test.go
- cmd/sfncli/test_scripts/stdout_empty_output.sh
> Treat empty worker output the same as empty object '{}'

- cmd/sfncli/sfncli.go
originally this was here to meter polling to `getactivitytask`. In reality `getactivitytask` blocks and does its own polling, so the ticker just ends up delaying the time between finishing a task and getting a new one.
> get rid of ticker

- cmd/sfncli/sfncli.go
sometimes the context finishes while we're sending a heartbeat: https://production--haproxy-logs.int.clever.com/_plugin/kibana/#/discover?_g=(refreshInterval:(display:Off,pause:!f,section:0,value:0),time:(from:now-1h,mode:quick,to:now))&_a=(columns:!(rawlog),index:%5Blogs-%5DYYYY-MM-DD,interval:auto,query:(query_string:(analyze_wildcard:!t,lowercase_expanded_terms:!f,query:'title:heartbeat-error-unknown')),sort:!(timestamp,desc))
> catch context canceled error

- cmd/sfncli/error_names.go
- cmd/sfncli/runner.go
- cmd/sfncli/runner_test.go
Allow commands to specify cause themselves. Error output is of the form `{"error": "whatever.whatever", "cause": "because things went wrong"}`.
> Custom errors

- .gitignore
- Gopkg.lock
- Makefile
- cmd/sfncli/cloudwatchreporter.go
- cmd/sfncli/cloudwatchreporter_test.go
- cmd/sfncli/sfncli.go
Currently sfncli reports active time as a cloudwatch metric. We've refined this into an estimate of percent of time spent active in the sfx dashboard, and it's been useful for determining which workers to scale up and down: https://app.signalfx.com/#/dashboard/DL8uwWYAcAA?variables%5B%5D=namespace%3Dworkflow_namespace:production&variables%5B%5D=team%3Dteam:&variables%5B%5D=resource%3Dresource:%5B%22mp*%22%5D&startTime=-8h&endTime=Now (see ActivityIdlePercent--if it's consistently low, we can scale up, if it's high, we can scale down)
This PR changes sfncli to directly report a cloudwatch metric that is percent of time spent active. This would let us:
1) remove sfx transformations to approximate this from time spent active
2) (more importantly) unblock autoscaling, since autoscaling …
> report active percent instead of active time

- cmd/sfncli/sfncli.go
We're seeing a 4-5 second delay between amazon recording an task assigned to a worker and the worker receiving it. The fact that we wait 20 seconds to send the first heartbeat plus the fact we have a 30 second heartbeat timeout means that we risk hitting the heartbeat timeout.
This PR changes it so that we send a heartbeat immediately upon receiving a task.
Go doesn't make it easy to create a timer with an immediate first tick, so I had to add a second heartbeat-related function
> send task heartbeat immediately after getting task

- cmd/sfncli/cloudwatchreporter.go
- cmd/sfncli/cloudwatchreporter_test.go
- cmd/sfncli/sfncli.go
right now if a worker takes less than a second to process a task, the `ActivePercent` metric tops out below 100%. This is because we rate limit calls to `GetActivityTask` to one per second, and we don't consider the time spent waiting to stay within this rate limit as "active" time.
This PR changes the metric to record time waiting to stay within this rate limit as active time.
> record wait time as active time

- make/sfncli.mk
- Added retries to sfncli download
- Added 30sec timeout 
- Shows error message when download fails
- Return non-zero exit code if download fails
Jira: https://clever.atlassian.net/browse/INFRA-2875
> INFRA-2875 — Made sfncli download more robust

- make/sfncli.mk
- Try to use user's `GITHUB_API_TOKEN` if possible to find latest version of sfncli
- Show explicit error if user doesn't have sfncli downloaded locally
- Show warning and continue working if a version of sfncli does exist locally
> Rate limit mitigation

- make/sfncli.mk
Folks have been seeing build failures because SFNCLI_LATEST is not getting set properly, e.g. https://circleci.com/gh/Clever/mpt-data-gator/378?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
Adding retries to try to fix it. Not sure if this fixed it since it's hard to test whether it failed the first time and succeeded on the retry, but it at least didn't make anything break https://github.com/Clever/mpt-data-gator/pull/104
> makefile retry check for latest

- VERSION
- cmd/sfncli/sfncli.go
cloudwatch metric streams to datadog copies AWS tags over to metrics in datadog, and it'd be helpful for activity metrics to have a team tag to create team-specific alerts
> add team tag to activities

- VERSION
- cmd/sfncli/error_names.go
Bugfix: Limit length of error fields per AWS limits.
AWS will return a validation error when trying to send a task failure with error or cause above
certain limits. sfncli should just defend itself against that by truncating.
Open to any feedback. Let me know also if you think `[truncated]` is too long - it's on the side of clarity compared to, say, `[...]`.
> Bugfix: Limit length of error fields per AWS limits.

- VERSION
- cmd/sfncli/runner.go
`exec-command-start` was converted to `TraceD` 3 years ago but I am pretty sure that it is never used. `exec-command-end` is currently the 2nd highest indexed log title, it is also never used.
We can get similar data directly from aws and it is also synced with datadog + the workflows dashboard covers this already so we should just delete these logs
> remove log that is never used

- Makefile
- make/sfncli.mk
Right now sfncli builds for old macs, and linux containers. Which means eng with m1 macs can't test anything that uses sfncli in their local dockers. 
This creates per arch releases and pulls in the right ones.
> create a release that will actually run on m1 macs for testing

- VERSION
- cmd/sfncli/sfncli.go
[Link to JIRA](https://clever.atlassian.net/browse/INFRANG-6403)
- Staging load test was failing due to throttling error thrown by step fn API
- We have a bunch of these error going back weeks where the number of API calls exceeds the provisioned capacity for the sfnapi.SendTaskHeartbeat
- This change should reduce the number of API calls by increasing the interval between heartbeat requests
- Changes the heartbeat interval
- Relevant metric to check: [link](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#metricsV2?graph=~(metrics~(~(~(expression~'m2*20*2a*2060~label~'Refill*20capacity*20per*20minute~id~'e1~yAxis~'right))~(~'AWS*2fStates~'ThrottledEvents~'APIName~'SendTaskHeartbeat~(yAxis~'right~id~'m1))~(~'.~'ProvisionedRefillRate~'.~'.~(yAxis~'right~stat~'Averag …
> increase heartbeat interval to manage throttling

- Makefile
- cmd/sfncli/runner.go
[Link to JIRA](https://clever.atlassian.net/browse/INFRANG-6403)
- Followup to https://github.com/Clever/sfncli/pull/114 (was failing master merge)
- Changes the heartbeat interval
- Relevant metric to check: [link](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#metricsV2?graph=~(metrics~(~(~(expression~'m2*20*2a*2060~label~'Refill*20capacity*20per*20minute~id~'e1~yAxis~'right))~(~'AWS*2fStates~'ThrottledEvents~'APIName~'SendTaskHeartbeat~(yAxis~'right~id~'m1))~(~'.~'ProvisionedRefillRate~'.~'.~(yAxis~'right~stat~'Average~id~'m2~visible~false))~(~'.~'ConsumedCapacity~'.~'.~(yAxis~'right~id~'m4)))~view~'timeSeries~stacked~false~region~'us-west-2~stat~'Sum~period~60~start~'-PT72H~end~'P0D)&query=~'*7bAWS*2fStates*2cAPIName*7d)
- Verify post rollout 
building with …
> Followup to increase heartbeat interval

- .circleci/config.yml
- Makefile
- cmd/sfncli/runner.go
- go.mod
- go.sum
- golang.mk
- tools/tools.go
https://clever.atlassian.net/browse/INFRANG-5578
This PR updates go to version 1.21. Welcome to the future. 
as part of the migration, we are testing against the dependencies
#
> upgrade to go 1.21

- Makefile
- VERSION
https://clever.atlassian.net/browse/INFRANG-6568
Proper release of the go 1.21 update along with minor version bump. 
This was tested as a pre-release
Release as latest and then pull into workers.
> go 1.21 update

- make/sfncli.mk
https://clever.atlassian.net/browse/INFRANG-6600
remove arch from sfncli.mk it's breaking things
This was a poorly thought through attempt at getting an sfncli that we build to work on m1 macs etc, but it didn’t work and broke other things so 🪓 
```bash
circleci@5fe17d98359f:~/go/src/github.com/Clever/redshift-to-postgres$ make build
rm -f bin/redshift-to-postgres
Checking for sfncli updates...
Updating sfncli...
Successfully updated sfncli to v0.8.0
mkdir -p bin
cp config.yml bin/config.yml
cp snowflake-config.yml bin/snowflake-config.yml
cp kvconfig.yml bin/
go build -o bin/redshift-to-postgres github.com/Clever/redshift-to-postgres
```
Merge
For repos erroring when getting sfncli have them run
`make sfncli-update-makefile`
> remove arch var from sfncli.ml
